/*
 Navicat Premium Dump SQL

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 180004 (180004)
 Source Host           : localhost:5432
 Source Catalog        : hify
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 180004 (180004)
 File Encoding         : 65001

 Date: 06/06/2026 18:34:27
*/


-- ----------------------------
-- Table structure for t_agent
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_agent";
CREATE TABLE "public"."t_agent" (
                                    "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                        INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                    "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
                                    "description" varchar(500) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                    "system_prompt" text COLLATE "pg_catalog"."default" NOT NULL,
                                    "model_config_id" int8 NOT NULL,
                                    "temperature" numeric(3,2) NOT NULL DEFAULT 0.70,
                                    "max_tokens" int4 NOT NULL DEFAULT 2048,
                                    "max_context_turns" int4 NOT NULL DEFAULT 10,
                                    "enabled" bool NOT NULL DEFAULT true,
                                    "created_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    "updated_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    "deleted" int2 NOT NULL DEFAULT 0
)
;
ALTER TABLE "public"."t_agent" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_agent"."deleted" IS '逻辑删除：0=未删 1=已删';
COMMENT ON COLUMN "public"."t_agent"."system_prompt" IS '角色指令，可以很长';
COMMENT ON COLUMN "public"."t_agent"."model_config_id" IS '绑定的模型配置';
COMMENT ON COLUMN "public"."t_agent"."temperature" IS '0.00~1.00';
COMMENT ON COLUMN "public"."t_agent"."max_context_turns" IS '保留最近几轮上下文';
COMMENT ON TABLE "public"."t_agent" IS 'Agent 配置';

-- ----------------------------
-- Table structure for t_agent_tool
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_agent_tool";
CREATE TABLE "public"."t_agent_tool" (
                                         "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                             INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                         "agent_id" int8 NOT NULL,
                                         "tool_id" int8 NOT NULL,
                                         "created_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
ALTER TABLE "public"."t_agent_tool" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_agent_tool"."tool_id" IS '关联 mcp_server.id';
COMMENT ON TABLE "public"."t_agent_tool" IS 'Agent 与工具关联';

-- ----------------------------
-- Table structure for t_chat_message
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_chat_message";
CREATE TABLE "public"."t_chat_message" (
                                           "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                           "session_id" int8 NOT NULL,
                                           "role" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
                                           "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                           "tokens" int4 NOT NULL DEFAULT 0,
                                           "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                           "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                           "deleted" int2 NOT NULL DEFAULT 0
)
;
ALTER TABLE "public"."t_chat_message" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_chat_message"."id" IS '主键';
COMMENT ON COLUMN "public"."t_chat_message"."session_id" IS '关联 t_chat_session.id';
COMMENT ON COLUMN "public"."t_chat_message"."role" IS '角色：user | assistant | tool';
COMMENT ON COLUMN "public"."t_chat_message"."content" IS '消息内容';
COMMENT ON COLUMN "public"."t_chat_message"."tokens" IS '本条消息消耗的 tokens';
COMMENT ON TABLE "public"."t_chat_message" IS '对话消息（游标分页，禁止 LIMIT offset）';

-- ----------------------------
-- Table structure for t_chat_session
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_chat_session";
CREATE TABLE "public"."t_chat_session" (
                                           "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                           "agent_id" int8 NOT NULL,
                                           "title" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '新对话'::character varying,
                                           "summary" varchar(512) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                           "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                           "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                           "deleted" int2 NOT NULL DEFAULT 0
)
;
ALTER TABLE "public"."t_chat_session" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_chat_session"."id" IS '主键';
COMMENT ON COLUMN "public"."t_chat_session"."agent_id" IS '关联 t_agent.id';
COMMENT ON COLUMN "public"."t_chat_session"."title" IS '会话标题';
COMMENT ON COLUMN "public"."t_chat_session"."summary" IS '摘要（首条消息自动截取）';
COMMENT ON TABLE "public"."t_chat_session" IS '对话会话';

-- ----------------------------
-- Table structure for t_demo_item
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_demo_item";
CREATE TABLE "public"."t_demo_item" (
                                        "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                        "name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
                                        "status" int4 NOT NULL DEFAULT 0,
                                        "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                        "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                        "deleted" int2 NOT NULL DEFAULT 0
)
;
ALTER TABLE "public"."t_demo_item" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_demo_item"."id" IS '主键';
COMMENT ON COLUMN "public"."t_demo_item"."name" IS '名称';
COMMENT ON COLUMN "public"."t_demo_item"."status" IS '状态';
COMMENT ON TABLE "public"."t_demo_item" IS 'CRUD 演示表';

-- ----------------------------
-- Table structure for t_mcp_server
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_mcp_server";
CREATE TABLE "public"."t_mcp_server" (
                                         "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                             INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                         "name" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
                                         "description" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                         "type" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
                                         "command" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                         "url" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                         "args" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '[]'::character varying,
                                         "env_vars" varchar(2048) COLLATE "pg_catalog"."default" NOT NULL DEFAULT '{}'::character varying,
                                         "enabled" bool NOT NULL DEFAULT true,
                                         "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                         "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                         "deleted" int2 NOT NULL DEFAULT 0
)
;
ALTER TABLE "public"."t_mcp_server" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_mcp_server"."id" IS '主键';
COMMENT ON COLUMN "public"."t_mcp_server"."name" IS 'MCP 服务名称';
COMMENT ON COLUMN "public"."t_mcp_server"."description" IS '用途描述';
COMMENT ON COLUMN "public"."t_mcp_server"."type" IS '连接类型：stdio | sse | http';
COMMENT ON COLUMN "public"."t_mcp_server"."command" IS 'stdio：启动命令，如 uvx mcp-server-fetch';
COMMENT ON COLUMN "public"."t_mcp_server"."url" IS 'sse/http：服务地址';
COMMENT ON COLUMN "public"."t_mcp_server"."args" IS 'JSON 数组：命令行参数';
COMMENT ON COLUMN "public"."t_mcp_server"."env_vars" IS 'JSON 对象：注入的环境变量';
COMMENT ON TABLE "public"."t_mcp_server" IS 'MCP 工具服务配置';

-- ----------------------------
-- Table structure for t_model_config
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_model_config";
CREATE TABLE "public"."t_model_config" (
                                           "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                           "provider_id" int8 NOT NULL,
                                           "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
                                           "model_id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
                                           "context_size" int4,
                                           "extra_params" jsonb,
                                           "enabled" bool DEFAULT true,
                                           "created_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           "updated_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           "deleted" int2 DEFAULT 0
)
;
ALTER TABLE "public"."t_model_config" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_model_config"."id" IS '主键';
COMMENT ON COLUMN "public"."t_model_config"."provider_id" IS '所属供应商 ID';
COMMENT ON COLUMN "public"."t_model_config"."name" IS '展示名，如 GPT-4o';
COMMENT ON COLUMN "public"."t_model_config"."model_id" IS '调用时传给 API 的值';
COMMENT ON COLUMN "public"."t_model_config"."context_size" IS '上下文窗口大小（token 数）';
COMMENT ON COLUMN "public"."t_model_config"."extra_params" IS '模型级别扩展参数';
COMMENT ON COLUMN "public"."t_model_config"."enabled" IS '0=禁用 1=启用';
COMMENT ON TABLE "public"."t_model_config" IS '模型配置';

-- ----------------------------
-- Table structure for t_provider
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_provider";
CREATE TABLE "public"."t_provider" (
                                       "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                           INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                       "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
                                       "type" varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
                                       "base_url" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
                                       "auth_config" jsonb,
                                       "enabled" bool DEFAULT true,
                                       "created_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       "updated_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       "deleted" int2 DEFAULT 0
)
;
ALTER TABLE "public"."t_provider" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_provider"."id" IS '主键';
COMMENT ON COLUMN "public"."t_provider"."name" IS '供应商名称，唯一';
COMMENT ON COLUMN "public"."t_provider"."type" IS 'OPENAI/ANTHROPIC/OLLAMA/OPENAI_COMPATIBLE';
COMMENT ON COLUMN "public"."t_provider"."base_url" IS 'API 基础地址';
COMMENT ON COLUMN "public"."t_provider"."auth_config" IS '鉴权配置，结构按 type 不同';
COMMENT ON COLUMN "public"."t_provider"."enabled" IS '0=禁用 1=启用';
COMMENT ON TABLE "public"."t_provider" IS '模型提供商';

-- ----------------------------
-- Table structure for t_provider_health
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_provider_health";
CREATE TABLE "public"."t_provider_health" (
                                              "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                  INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                              "provider_id" int8 NOT NULL,
                                              "status" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'UNKNOWN'::character varying,
                                              "last_check_at" timestamp(6),
                                              "last_success_at" timestamp(6),
                                              "fail_count" int4 DEFAULT 0,
                                              "latency_ms" int4,
                                              "error_message" varchar(500) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
                                              "updated_at" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
ALTER TABLE "public"."t_provider_health" OWNER TO "zyy";
COMMENT ON COLUMN "public"."t_provider_health"."id" IS '主键';
COMMENT ON COLUMN "public"."t_provider_health"."provider_id" IS '供应商 ID，唯一索引';
COMMENT ON COLUMN "public"."t_provider_health"."status" IS 'UP/DOWN/DEGRADED/UNKNOWN';
COMMENT ON COLUMN "public"."t_provider_health"."last_check_at" IS '最后探测时间';
COMMENT ON COLUMN "public"."t_provider_health"."last_success_at" IS '最后成功时间';
COMMENT ON COLUMN "public"."t_provider_health"."fail_count" IS '连续失败次数';
COMMENT ON COLUMN "public"."t_provider_health"."latency_ms" IS '最近一次延迟 ms';
COMMENT ON COLUMN "public"."t_provider_health"."error_message" IS '最近失败原因';
COMMENT ON TABLE "public"."t_provider_health" IS '供应商健康状态';

-- ----------------------------
-- Indexes structure for table t_agent
-- ----------------------------
CREATE INDEX "idx_agent_model_config_id" ON "public"."t_agent" USING btree (
    "model_config_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_agent
-- ----------------------------
CREATE TRIGGER "trigger_agent_update_updated_at" BEFORE UPDATE ON "public"."t_agent"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Uniques structure for table t_agent
-- ----------------------------
ALTER TABLE "public"."t_agent" ADD CONSTRAINT "agent_name_key" UNIQUE ("name");

-- ----------------------------
-- Primary Key structure for table t_agent
-- ----------------------------
ALTER TABLE "public"."t_agent" ADD CONSTRAINT "agent_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_agent_tool
-- ----------------------------
CREATE INDEX "idx_agent_tool_agent_id" ON "public"."t_agent_tool" USING btree (
    "agent_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Uniques structure for table t_agent_tool
-- ----------------------------
ALTER TABLE "public"."t_agent_tool" ADD CONSTRAINT "uk_agent_tool" UNIQUE ("agent_id", "tool_id");

-- ----------------------------
-- Primary Key structure for table t_agent_tool
-- ----------------------------
ALTER TABLE "public"."t_agent_tool" ADD CONSTRAINT "agent_tool_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_chat_message
-- ----------------------------
CREATE INDEX "idx_chat_message_session_deleted_created" ON "public"."t_chat_message" USING btree (
    "session_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
    "deleted" "pg_catalog"."bool_ops" ASC NULLS LAST,
    "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_chat_message
-- ----------------------------
CREATE TRIGGER "trigger_t_chat_message_update_updated_at" BEFORE UPDATE ON "public"."t_chat_message"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_chat_message
-- ----------------------------
ALTER TABLE "public"."t_chat_message" ADD CONSTRAINT "t_chat_message_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_chat_session
-- ----------------------------
CREATE INDEX "idx_chat_session_agent_deleted_updated" ON "public"."t_chat_session" USING btree (
    "agent_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
    "deleted" "pg_catalog"."bool_ops" ASC NULLS LAST,
    "updated_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_chat_session
-- ----------------------------
CREATE TRIGGER "trigger_t_chat_session_update_updated_at" BEFORE UPDATE ON "public"."t_chat_session"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_chat_session
-- ----------------------------
ALTER TABLE "public"."t_chat_session" ADD CONSTRAINT "t_chat_session_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table t_demo_item
-- ----------------------------
CREATE TRIGGER "trigger_t_demo_item_update_updated_at" BEFORE UPDATE ON "public"."t_demo_item"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_demo_item
-- ----------------------------
ALTER TABLE "public"."t_demo_item" ADD CONSTRAINT "t_demo_item_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_mcp_server
-- ----------------------------
CREATE INDEX "idx_mcp_server_type_deleted" ON "public"."t_mcp_server" USING btree (
    "type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "deleted" "pg_catalog"."bool_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_mcp_server
-- ----------------------------
CREATE TRIGGER "trigger_t_mcp_server_update_updated_at" BEFORE UPDATE ON "public"."t_mcp_server"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_mcp_server
-- ----------------------------
ALTER TABLE "public"."t_mcp_server" ADD CONSTRAINT "t_mcp_server_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table t_model_config
-- ----------------------------
CREATE TRIGGER "trigger_t_model_config_update_updated_at" BEFORE UPDATE ON "public"."t_model_config"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_model_config
-- ----------------------------
ALTER TABLE "public"."t_model_config" ADD CONSTRAINT "t_model_config_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_provider
-- ----------------------------
CREATE UNIQUE INDEX "idx_provider_name" ON "public"."t_provider" USING btree (
    "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_provider
-- ----------------------------
CREATE TRIGGER "trigger_t_provider_update_updated_at" BEFORE UPDATE ON "public"."t_provider"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_provider
-- ----------------------------
ALTER TABLE "public"."t_provider" ADD CONSTRAINT "t_provider_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table t_provider_health
-- ----------------------------
CREATE UNIQUE INDEX "idx_provider_health_provider_id" ON "public"."t_provider_health" USING btree (
    "provider_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Triggers structure for table t_provider_health
-- ----------------------------
CREATE TRIGGER "trigger_t_provider_health_update_updated_at" BEFORE UPDATE ON "public"."t_provider_health"
    FOR EACH ROW
    EXECUTE PROCEDURE "public"."update_updated_at_column"();

-- ----------------------------
-- Primary Key structure for table t_provider_health
-- ----------------------------
ALTER TABLE "public"."t_provider_health" ADD CONSTRAINT "t_provider_health_pkey" PRIMARY KEY ("id");
