-- ===== PostgreSQL + pgvector 专有表（不与 MySQL 重复） =====

-- 确保扩展（每个库执行一次）
CREATE EXTENSION IF NOT EXISTS vector;

-- 文档切片 + 向量（1536 维 = text-embedding-3-small，后续可 ALTER 调整）
DROP TABLE IF EXISTS t_document_chunk;
CREATE TABLE t_document_chunk (
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id int8         NOT NULL,
    chunk_index int4         NOT NULL,
    content     text         NOT NULL,
    embedding   vector(1536) NOT NULL,
    token_count int4         NOT NULL DEFAULT 0,
    deleted     int2         NOT NULL DEFAULT 0,
    created_at  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chunk_document ON t_document_chunk (document_id, deleted);

-- Agent 关联知识库（t_agent 可能在 MySQL 建表时已含此列，此处用 ADD IF NOT EXISTS）
-- ALTER TABLE t_agent ADD COLUMN IF NOT EXISTS knowledge_base_id int8;
COMMENT ON TABLE t_document_chunk IS '文档切片 + 向量';

-- pgvector ivfflat 余弦索引（先导数据再建，初始 lists=100）
-- CREATE INDEX idx_chunk_embedding_cos ON t_document_chunk
--     USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
